### PR TITLE
Add ngram and edgengram support

### PR DESCRIPTION
**Pull request by natcohen**
It's probably a miserable attempt but at least it's an attempt! I am not sure to understand the code but this is what I came up with.

Since the ngram tokenizer takes a `Reader` as an input, I have copied the Japanese analyzer that sends `null` (for what I think is the reader) but I am not sure that it's correct. Regarding the minimum gram and maximum gram parameters, I thought I could pass it through the CouchDB index file with options `mingram` and `maxgram`.

### CODE REVIEW

**Comment by rnewson** [comment]
Hm, not sure that is right, best add a test. For the current set of analyzers we have https://github.com/cloudant-labs/clouseau/blob/master/src/test/scala/com/cloudant/clouseau/SupportedAnalyzersSpec.scala which is just confirming that the factory method produces an object of the right type, and you can at least verify that the options are set.

**Comment by rnewson** [comment]
does this compile for you? It doesn't for me. (A Tokenizer isn't an Analyzer fwiw).

**Comment by rnewson** [comment]
Something like this.

```
diff --git a/src/main/scala/com/cloudant/clouseau/SupportedAnalyzers.scala b/src/main/scala/com/cloudant/clouseau/SupportedAnalyzers.scala
index 8f81b5c..4bd2c47 100644
--- a/src/main/scala/com/cloudant/clouseau/SupportedAnalyzers.scala
+++ b/src/main/scala/com/cloudant/clouseau/SupportedAnalyzers.scala
@@ -12,22 +12,23 @@

 package com.cloudant.clouseau

+import java.io.Reader
 import java.util.{ Set => JSet }
 import org.apache.log4j.Logger
 import org.apache.lucene.analysis.Analyzer
 import org.apache.lucene.analysis.util.CharArraySet
 import scala.collection.JavaConversions._

-import org.apache.lucene.analysis.ngram.NGramTokenizer
-import org.apache.lucene.analysis.core.KeywordAnalyzer
-import org.apache.lucene.analysis.core.SimpleAnalyzer
-import org.apache.lucene.analysis.core.WhitespaceAnalyzer
+import org.apache.lucene.analysis.Analyzer.TokenStreamComponents
 import org.apache.lucene.analysis.ar.ArabicAnalyzer
 import org.apache.lucene.analysis.bg.BulgarianAnalyzer
 import org.apache.lucene.analysis.br.BrazilianAnalyzer
 import org.apache.lucene.analysis.ca.CatalanAnalyzer
 import org.apache.lucene.analysis.cjk.CJKAnalyzer
 import org.apache.lucene.analysis.cn.smart.SmartChineseAnalyzer
+import org.apache.lucene.analysis.core.KeywordAnalyzer
+import org.apache.lucene.analysis.core.SimpleAnalyzer
+import org.apache.lucene.analysis.core.WhitespaceAnalyzer
 import org.apache.lucene.analysis.cz.CzechAnalyzer
 import org.apache.lucene.analysis.da.DanishAnalyzer
 import org.apache.lucene.analysis.de.GermanAnalyzer
@@ -47,6 +48,7 @@ import org.apache.lucene.analysis.id.IndonesianAnalyzer
 import org.apache.lucene.analysis.it.ItalianAnalyzer
 import org.apache.lucene.analysis.ja.JapaneseAnalyzer
 import org.apache.lucene.analysis.lv.LatvianAnalyzer
+import org.apache.lucene.analysis.ngram.NGramTokenizer
 import org.apache.lucene.analysis.nl.DutchAnalyzer
 import org.apache.lucene.analysis.no.NorwegianAnalyzer
 import org.apache.lucene.analysis.pl.PolishAnalyzer
@@ -108,7 +110,12 @@ object SupportedAnalyzers {
     case "whitespace" =>
       Some(new WhitespaceAnalyzer(IndexService.version))
     case "ngram" =>
-      Some(new NGramTokenizer(IndexService.version, null, options.get("mingram"), options.get("maxgram")))
+      Some(new Analyzer() {
+        def createComponents(fieldName: String, reader: Reader): TokenStreamComponents = {
+          new TokenStreamComponents(new NGramTokenizer(IndexService.version, reader,
+            options.get("mingram").asInstanceOf[Int], options.get("maxgram").asInstanceOf[Int]))
+        }
+      })
     case "arabic" =>
       options.get("stopwords") match {
         case Some(stopwords: List[String]) =>
```

**Comment by rnewson** [comment]
noting that the options will ultimately come from the analyzer definition in the design doc

**Comment by natcohen** [comment]
Well... I don't know Scala at all and the last time I wrote a line of Java was 15 years ago! I don't even know how to compile it so I just tried to mimic what you did for the other analyzers. Obviously I was far to be right.

Regarding the tokenizer and analyzer difference, I agree that they are different in their functions but for CouchDB admins, it's more a semantic difference than a technical difference. Putting "mingram" and "maxgram" in the analyzer definition is not semantically correct but it doesn't make a real difference for CouchDB admins.

I can still try to add a test but based on what I did for adding the tokenizers, I m not sure I completely understand the mechanics behind code...

**Comment by rnewson** [comment]
sorry, I meant that a Tokenizer is of the wrong type so it does not compile (much less work) in the original commit. Not semantics at all. :)

**Comment by rnewson** [comment]
this said, if you aren't able to compile you won't be able to run the tests needed either.

**Comment by natcohen** [comment]
I've made the changes you suggested... can I add the following to the test?

```
"ngram" in {
      createAnalyzer("ngram") must haveClass[Some[TokenStreamComponents]]
      createAnalyzer("ngram") must haveClass[Some[NGramTokenizer]]
}
"edgengram" in {
      createAnalyzer("edgengram") must haveClass[Some[TokenStreamComponents]]
      createAnalyzer("edgengram") must haveClass[Some[EdgeNGramTokenizer]]
}
```

I feel sorry, I seem to generate more work for you with my mistakes! I'm just trying to have ngram for my projects and can't really wait until CouchDB 4 comes out. I'd love to learn Scala but unfortunately I don't really have time to start from scratch!

**Comment by rnewson** [comment]
add them, verify that they pass locally, then update the PR if they do. :)

**Comment by natcohen** [comment]
What do you mean by pass locally? I don't know how to build it... Could anyone run a test?

PS I've added the test

**Comment by rnewson** [comment]
It is is unusual for a contributor to not even compile their work. Can you please install java (6 or 7) and maven and try `mvn test`?

**Comment by rnewson** [comment]
Ok I set up CI with Github Actions, you'll need to nudge the PR to get it to attempt a build. I suggest you squash your 3 commits into one and them force push it to the branch, that should do it.

**Comment by rnewson** [comment]
that CI passes on master (i.e, without these changes) but is a bit flaky, took three retries. Not sure why.

**Comment by natcohen** [comment]
I have tried to build (`mvn test`) but I'm getting the following error... 

```
Downloaded from CloudantPublicRepo: https://maven.cloudant.com/repo/org/scala-lang/scala-compiler/2.9.1/scala-compiler-2.9.1.pom (1.7 kB at 8.7 kB/s)
[ERROR] error: error while loading AnnotatedElement, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
[INFO] (bad constant pool tag 18 at byte 76)
[ERROR] error: error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
[INFO] (bad constant pool tag 18 at byte 10)
[ERROR] error: error while loading Pattern, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/rt.jar(java/util/regex/Pattern.class)' is broken
[INFO] (bad constant pool tag 18 at byte 1756)
[ERROR] error: error while loading ConcurrentMap, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/rt.jar(java/util/concurrent/ConcurrentMap.class)' is broken
[INFO] (bad constant pool tag 18 at byte 61)
[ERROR] /clouseau/src/main/scala/com/cloudant/clouseau/IndexCleanupService.scala:60: error: value matcher is not a member of java.util.regex.Pattern
[ERROR]     val m = includePattern.matcher(fileOrDir.getAbsolutePath)
[ERROR]                            ^
[ERROR] error: error while loading Entry, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/rt.jar(java/util/Map$Entry.class)' is broken
[INFO] (bad constant pool tag 18 at byte 10)
[ERROR] /clouseau/src/main/scala/com/cloudant/clouseau/IndexManagerService.scala:32: error: java.util.Map.Entry does not take type parameters
[ERROR]       override def removeEldestEntry(eldest: Entry[String, Pid]): Boolean = {
[ERROR]                                              ^
[ERROR] /clouseau/src/main/scala/com/cloudant/clouseau/IndexService.scala:585: error: type mismatch;
[ERROR]  found   : String
[ERROR]  required: java.lang.CharSequence
[ERROR]     IndexService.SORT_FIELD_RE.findFirstMatchIn(field) match {
[ERROR]                                                 ^
[ERROR] error: error while loading Comparator, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/rt.jar(java/util/Comparator.class)' is broken
[INFO] (bad constant pool tag 18 at byte 20)
[ERROR] /clouseau/src/main/scala/com/cloudant/clouseau/IndexService.scala:669: error: could not find implicit value for parameter num: Numeric[Long]
[ERROR]     sizes.sum
[ERROR]           ^
[ERROR] /clouseau/src/main/scala/com/cloudant/clouseau/Utils.scala:29: error: overloaded method constructor BytesRef with alternatives:
[ERROR]   (java.lang.CharSequence)org.apache.lucene.util.BytesRef <and>
[ERROR]   (Int)org.apache.lucene.util.BytesRef <and>
[ERROR]   (Array[Byte])org.apache.lucene.util.BytesRef
[ERROR]  cannot be applied to (String)
[ERROR]     new BytesRef(string)
[ERROR]     ^
[ERROR] 11 errors found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.737 s
[INFO] Finished at: 2020-04-02T01:35:44+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.0:compile (scala-compile-first) on project clouseau: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by natcohen** [comment]
My bad, I had jdk 8. I tried with 7 and here is what I got:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< com.cloudant:clouseau >------------------------
[INFO] Building clouseau 2.17.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- scalariform-maven-plugin:0.1.4:format (default) @ clouseau ---
[INFO] Modified 0 of 22 .scala files
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ clouseau ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /clouseau/src/main/resources
[INFO] 
[INFO] --- scala-maven-plugin:3.1.0:add-source (scala-compile-first) @ clouseau ---
[INFO] 
[INFO] --- scala-maven-plugin:3.1.0:compile (scala-compile-first) @ clouseau ---
[INFO] /clouseau/src/main/scala:-1: info: compiling
[INFO] Compiling 13 source files to /clouseau/target/classes at 1585787166967
[WARNING] warning: there were 7 deprecation warnings; re-run with -deprecation for details
[WARNING] warning: there were 49 unchecked warnings; re-run with -unchecked for details
[WARNING] two warnings found
[INFO] prepare-compile in 0 s
[INFO] compile in 19 s
[INFO] 
[INFO] --- maven-compiler-plugin:2.4:compile (default-compile) @ clouseau ---
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-core/2.0.9/maven-core-2.0.9.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-toolchain/1.0/maven-toolchain-1.0.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/1.8.6/plexus-compiler-api-1.8.6.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/1.8.6/plexus-compiler-manager-1.8.6.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/1.8.6/plexus-compiler-javac-1.8.6.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.790 s
[INFO] Finished at: 2020-04-02T02:26:27+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.4:compile (default-compile) on project clouseau: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:2.4:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:2.4 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-compiler-plugin:jar:2.4 -> org.apache.maven:maven-core:jar:2.0.9: Failed to read artifact descriptor for org.apache.maven:maven-core:jar:2.0.9: Could not transfer artifact org.apache.maven:maven-core:pom:2.0.9 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/maven-core/2.0.9/maven-core-2.0.9.pom: Received fatal alert: protocol_version -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by rnewson** [comment]
ah, try with 7. I think JDK 6 can't do TLS 1.2 and all the maven repos now require that, like many places.

I set up CI here yesterday so you can now update the PR and have github run the test suite for you.

**Comment by natcohen** [comment]
I have merged your master into my patch-1 branch but it doesn't build and I don't know how to re-run it in github. Since it didn't work twice for you, it might be the same for me...

**Comment by rnewson** [comment]
ok, this is fun, those tests pass but they shouldn't. It turns out the tests are wrong and we're only checking we get `Some` back, which we always do, and not the type of data inside that Some.

**Comment by natcohen** [comment]
Ok, but does the ngram integration work?

**Comment by rnewson** [comment]
No, I don't think so.

**Comment by natcohen** [comment]
what's misisng?

**Comment by rnewson** [comment]
a test that demonstrates it works. :)

**Comment by natcohen** [comment]
Well, I’d love to test it but I don’t even succeed to build it...I’ve tried to run ‘mvn test’ but it fails!

If I have the binaries, I can stick them into my server and test. But if you tell me that all the tests are actually not working even for the other analyzers, I don’t know how I can come up with a solution knowing that I have absolutely no experience with Scala!

Any suggestion?

**Comment by rnewson** [comment]
I don't have the time to develop this feature enhancement myself, so if you can build without the test (`mvn package -DskipTests`) and actually try the two new analyzers in a couchdb/clouseau setup, that should help you validate this work. Report back when you have an update?

**Comment by natcohen** [comment]
The problem is that I tried many things to build but I keep getting errors (even with jdk 7)! If you share the binaries, I can test them very quickly... but debugging building errors on a platform I'm not familiar with might take hours/days. Can you share them? I can give you my email address or through a wetransfer.

Here is my error (I'm on OSX):
```
> mvn package -DskipTests
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< com.cloudant:clouseau >------------------------
[INFO] Building clouseau 2.17.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.2/maven-jar-plugin-2.2.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.302 s
[INFO] Finished at: 2020-04-02T21:34:25+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-jar-plugin:2.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-jar-plugin:jar:2.2: Could not transfer artifact org.apache.maven.plugins:maven-jar-plugin:pom:2.2 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.2/maven-jar-plugin-2.2.pom: Received fatal alert: protocol_version -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by rnewson** [comment]
try with docker, this ran all the tests successfully for me;

FROM debian:jessie
RUN apt-get -q update && apt-get -y install openjdk-7-jdk maven erlang git
RUN git clone https://github.com/cloudant-labs/clouseau
WORKDIR clouseau
RUN mvn package

**Comment by natcohen** [comment]
Ok... I've succeeded to build on Debian as you suggested. I've tried to put it into my Clouseau instance and built the index like this:

```
"indexes": {
    "index_name": {
      "analyzer": {
        "name": "ngram",
        "mingram": 1,
        "maxgram": 3
      },
      "index": "function(doc) {...}"
    }
}
```

But I get the following error:

```
java.lang.ClassCastException: scala.Some cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(Unknown Source)
	at com.cloudant.clouseau.SupportedAnalyzers$$anon$1.createComponents(SupportedAnalyzers.scala:117)
```

Seems like the `.asInstanceOf[Int]` cast is not well accepted on my options or I'm not setting my options properly. Any hint?

**Comment by rnewson** [comment]
`options.get("mingram").get.asInstanceOf[Int]` but that is not great Scala, you'll need to read and learn a little bit to propose something better there.

**Comment by natcohen** [comment]
So I've tried to replace the cast and it builds and doesn't return any error when I query. The problem now is no matter what I query, it always returns all the objects indexed! I'm completely lost here...

**Comment by rnewson** [comment]
perhaps better leave it as an Issue rather than a Pull Request.

**Comment by natcohen** [comment]
Filing an issue on a pull request? Everything works when the ngram is not used so it’s only related to that specific pull request. It sounds wrong to me to file an issue on something I’m trying to add. I can definitely do that but it seems that this project has been abandoned.

Is there any timeline for CouchDB 4? I feel powerless  :o(

**Comment by rnewson** [comment]
I'm sorry you feel powerless, but all I'm saying here is that I am not developing this feature for you. If you can contribute a working version of this, I will review it, but so far it feels like I am doing the bulk of the work. You've filed an issue requesting this, and that seems to be as far as you can take it, and that's absolutely fine. Clouseau is hard to use, it's coupled to old versions of the JDK and several obsolete libraries, it's end of life for multiple reasons.

CouchDB 4.0 is not that far off, but the nextgen search also does not have ngram/edgegram support. That project is https://github.com/cloudant-labs/search3-java/ btw if you are more familiar with Java than Scala.

**Comment by natcohen** [comment]
I totally understand! But why not adding these tokenizers to the new version? Is it that difficult to implement?

Ngram/edgengram are used for auto-complete which is a key feature for a lot of use cases!

**Comment by rnewson** [comment]
You can file an issue about it on the search3-java project and/or a pull request if you are able to do the work, and I'll happily review it.

Adding this support isn't something I'm planning to spend my own time on at the moment.

**Comment by rnewson** [comment]
closing this. can be re-opened (or a new PR filed) if someone wants to pick it up.

**Pull request closed without merging**
